dist: xenial
language: csharp
solution: Epicoin.sln
mono: none
dotnet: 2.1.503
install:
 - dotnet restore
script:
 - dotnet build
 - dotnet test
 - dotnet pack "./Core/Epicoin Core.csproj" -c Release -o nugets
deploy:
  provider: releases
  api_key:
    secure: $GITACCESSTOKEN
  skip_cleanup: true
  file:
    - "./Core/bin/Release/netcoreapp2.1/*.dll"
    - "./nugets/*.nupkg"
  on:
    tags: true